apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: lightpink
  name: lightpink
  namespace: colors-webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lightpink
  template:
    metadata:
      labels:
        app: lightpink
    spec:
      containers:
      - image: jpetazzo/webcolor
        name: lightpink
        ports:
        - containerPort: 8000
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: lightpink
  name: lightpink
  namespace: colors-webapp
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: lightpink
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lightpink
  namespace: colors-webapp
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production

spec:
  ingressClassName: traefik
  rules:
  - host: colors.myfunnycluster.dynamic-dns.net
    http:
      paths:
      - backend:
          service:
            name: lightpink
            port:
              number: 8000
        path: /pink
        pathType: Exact
  tls:
  - hosts:
    - colors.myfunnycluster.dynamic-dns.net
    secretName: colors
